const branches = [
  { id: 1, name: 'Nilandhoo', regionId: 14 },
  { id: 2, name: 'Bilehdhoo', regionId: 14 },
  { id: 3, name: 'Feeali', regionId: 14 },
  { id: 4, name: 'Magoodhoo', regionId: 14 },
  { id: 5, name: 'Dharanboodhoo', regionId: 14 },
  { id: 6, name: 'Baarah', regionId: 1 },
  { id: 7, name: 'Filladhoo', regionId: 1 },
  { id: 8, name: 'Hoarafushi', regionId: 1 },
  { id: 9, name: 'Ihavandhoo', regionId: 1 },
  { id: 10, name: 'Maarandhoo', regionId: 1 },
  { id: 11, name: 'Molhadhoo', regionId: 1 },
  { id: 12, name: 'Muraidhoo', regionId: 1 },
  { id: 13, name: 'Thakandhoo', regionId: 1 },
  { id: 14, name: 'Thuraakunu', regionId: 1 },
  { id: 15, name: 'Uligam', regionId: 1 },
  { id: 16, name: 'Vashafaru', regionId: 1 },
  { id: 17, name: 'Kulhudhufushi', regionId: 2 },
  { id: 18, name: 'Finey', regionId: 2 },
  { id: 19, name: 'Hirimaradhoo', regionId: 2 },
  { id: 20, name: 'Kumundhoo', regionId: 2 },
  { id: 21, name: 'Kurinbi', regionId: 2 },
  { id: 22, name: 'Feevah', regionId: 3 },
  { id: 23, name: 'Feydhoo', regionId: 3 },
  { id: 24, name: 'Foakaidhoo', regionId: 3 },
  { id: 25, name: 'Goidhoo', regionId: 3 },
  { id: 26, name: 'Fodhdhoo', regionId: 4 },
  { id: 27, name: 'Henbadhoo', regionId: 4 },
  { id: 28, name: 'Holhudhoo', regionId: 4 },
  { id: 29, name: 'Kudafari', regionId: 4 },
  { id: 30, name: 'Nadella', regionId: 19 },
  { id: 31, name: 'Makunudhoo', regionId: 2 },
  { id: 32, name: 'Naavaidhoo', regionId: 2 },
  { id: 33, name: 'Nellaidhoo', regionId: 2 },
  { id: 34, name: 'Nolhivaram', regionId: 2 },
  { id: 35, name: 'Nolhivaramfaru', regionId: 2 },
  { id: 36, name: 'Vaikaradhoo', regionId: 2 },
  { id: 37, name: 'Kanditheem', regionId: 3 },
  { id: 38, name: 'Komandoo', regionId: 3 },
  { id: 39, name: 'Lhaimagu', regionId: 3 },
  { id: 40, name: 'Maaungoodhoo', regionId: 3 },
  { id: 41, name: 'Milandhoo', regionId: 3 },
  { id: 42, name: 'Narudhoo', regionId: 3 },
  { id: 43, name: 'Noomara', regionId: 3 },
  { id: 44, name: 'Maroshi', regionId: 3 },
  { id: 45, name: 'Bilehfahi', regionId: 3 },
  { id: 46, name: 'Rathafandhoo', regionId: 19 },
  { id: 47, name: 'Neykurendhoo', regionId: 2 },
  { id: 49, name: 'Dhidhdhoo', regionId: 1 },
  { id: 50, name: 'Kelaa', regionId: 1 },
  { id: 51, name: 'Utheem', regionId: 1 },
  { id: 52, name: 'Hanimaadhoo', regionId: 2 },
  { id: 53, name: 'Kendhikulhudhoo', regionId: 4 },
  { id: 54, name: 'Landhoo', regionId: 4 },
  { id: 55, name: 'Lhohi', regionId: 4 },
  { id: 56, name: 'Maafaru', regionId: 4 },
  { id: 57, name: 'Maalhendhoo', regionId: 4 },
  { id: 58, name: 'Magoodhoo', regionId: 4 },
  { id: 59, name: 'Manadhoo', regionId: 4 },
  { id: 60, name: 'Miladhoo', regionId: 4 },
  { id: 61, name: 'Velidhoo', regionId: 4 },
  { id: 62, name: 'Alifushi', regionId: 5 },
  { id: 63, name: 'Angolhitheemu', regionId: 5 },
  { id: 64, name: 'Fainu', regionId: 5 },
  { id: 65, name: 'Hulhudhuffaaru', regionId: 5 },
  { id: 66, name: 'Inguraidhoo', regionId: 5 },
  { id: 67, name: 'Innamaadhoo', regionId: 5 },
  { id: 68, name: 'Kinolhas', regionId: 5 },
  { id: 69, name: 'Maakurathu', regionId: 5 },
  { id: 70, name: 'Maduvvari', regionId: 5 },
  { id: 71, name: 'Rasgetheemu', regionId: 5 },
  { id: 72, name: 'Rasmaadhoo', regionId: 5 },
  { id: 73, name: 'Meedhoo', regionId: 5 },
  { id: 74, name: 'Vaadhoo', regionId: 5 },
  { id: 75, name: 'Dharavandhoo', regionId: 6 },
  { id: 76, name: 'Dhonfanu', regionId: 6 },
  { id: 77, name: 'Eydhafushi', regionId: 6 },
  { id: 78, name: 'Fehendhoo', regionId: 6 },
  { id: 79, name: 'Fulhadhoo', regionId: 6 },
  { id: 80, name: 'Goidhoo', regionId: 6 },
  { id: 81, name: 'Hithaadhoo', regionId: 6 },
  { id: 82, name: 'Kamadhoo', regionId: 6 },
  { id: 83, name: 'Kendhoo', regionId: 6 },
  { id: 84, name: 'Kihaadhoo', regionId: 6 },
  { id: 85, name: 'Kudarikilu', regionId: 6 },
  { id: 86, name: 'Maalhos', regionId: 6 },
  { id: 87, name: 'Thulhaadhoo', regionId: 6 },
  { id: 88, name: 'Hinnavaru', regionId: 7 },
  { id: 89, name: 'Kurendhoo', regionId: 7 },
  { id: 90, name: 'Naifaru', regionId: 7 },
  { id: 91, name: 'Olhuvelifushi', regionId: 7 },
  { id: 92, name: 'Veyvah', regionId: 13 },
  { id: 93, name: 'Naalaafushi', regionId: 13 },
  { id: 94, name: 'Mulak', regionId: 13 },
  { id: 95, name: 'Dhiggar', regionId: 13 },
  { id: 96, name: 'Muli', regionId: 13 },
  { id: 97, name: 'Maduvvaree', regionId: 13 },
  { id: 98, name: 'Raiymandhoo', regionId: 13 },
  { id: 99, name: 'Kolhufushi', regionId: 13 },
  { id: 100, name: 'Bandidhoo ', regionId: 15 },
  { id: 101, name: 'Hulhudheli ', regionId: 15 },
  { id: 102, name: 'Kudahuvadhoo', regionId: 15 },
  { id: 103, name: 'Meedhoo', regionId: 15 },
  { id: 104, name: 'Maaenboodhoo', regionId: 15 },
  { id: 105, name: 'Rinbudhoo', regionId: 15 },
  { id: 106, name: 'Buruni ', regionId: 16 },
  { id: 107, name: 'Dhiyamigili ', regionId: 16 },
  { id: 108, name: 'Gaadhifushi ', regionId: 16 },
  { id: 109, name: 'Kandoodhoo', regionId: 16 },
  { id: 110, name: 'Kinbidhoo ', regionId: 16 },
  { id: 111, name: 'Madifushi ', regionId: 16 },
  { id: 112, name: 'Omadhoo', regionId: 16 },
  { id: 113, name: 'Thimarafushi ', regionId: 16 },
  { id: 114, name: 'Vandhoo ', regionId: 16 },
  { id: 115, name: 'Vilufushi', regionId: 16 },
  { id: 116, name: 'Guraidhoo', regionId: 16 },
  { id: 117, name: 'Hirilandhoo', regionId: 16 },
  { id: 118, name: 'Veymandoo', regionId: 16 },
  { id: 119, name: 'Dhandhoo', regionId: 18 },
  { id: 120, name: 'Dhevvadhoo', regionId: 18 },
  { id: 121, name: 'Gemanafushi', regionId: 18 },
  { id: 122, name: 'Kanduhulhudhoo', regionId: 18 },
  { id: 123, name: 'Kolamaafushi', regionId: 18 },
  { id: 124, name: 'Kondey', regionId: 18 },
  { id: 125, name: 'Maamendhoo', regionId: 18 },
  { id: 126, name: 'Villingili', regionId: 18 },
  { id: 127, name: 'Nilandhoo', regionId: 18 },
  { id: 128, name: 'Faresmathoda', regionId: 19 },
  { id: 129, name: 'Fiyoreee', regionId: 19 },
  { id: 130, name: 'Gadhdhoo', regionId: 19 },
  { id: 131, name: 'Hoadehdhoo', regionId: 19 },
  { id: 132, name: 'Madaveli', regionId: 19 },
  { id: 133, name: 'Thinadhoo', regionId: 19 },
  { id: 134, name: 'Vaadhoo', regionId: 19 },
  { id: 135, name: 'Fuvahmulah', regionId: 20 },
  { id: 136, name: 'Isdhoo', regionId: 17 },
  { id: 137, name: 'Kalaidhoo', regionId: 17 },
  { id: 138, name: 'Maavah ', regionId: 17 },
  { id: 139, name: 'Hithadhoo', regionId: 21 },
  { id: 140, name: 'Maradhoo Feydhoo', regionId: 21 },
  { id: 141, name: 'Dhanbidhoo', regionId: 17 },
  { id: 142, name: 'Kunahandhoo ', regionId: 17 },
  { id: 143, name: 'Hulhumeedhoo', regionId: 21 },
  { id: 144, name: 'Maabaidhoo', regionId: 17 },
  { id: 145, name: 'Mundoo', regionId: 17 },
  { id: 146, name: 'Maamendhoo', regionId: 17 },
  { id: 147, name: 'Gan', regionId: 17 },
  { id: 148, name: 'Fonadhoo', regionId: 17 },
  { id: 149, name: 'Hithadhoo', regionId: 17 },
  { id: 150, name: 'Head Office', regionId: 9 },
  { id: 153, name: 'Funadhoo', regionId: 3 },
  { id: 154, name: 'Huraa', regionId: 8 },
  { id: 155, name: 'Mahibadhoo', regionId: 11 },
  { id: 156, name: 'Ungoofaaru', regionId: 5 },  
]

module.exports = branches